### ISSUE TITLE
有个使用问题想请教一下

### ISSUE THREAD

**Issue by Devil-AND** [soulqw/SoulPermission#12]
我在fragment中请求了一个拨电话的权限,但是楼主的onPermissionDenied()方法并没有走这个流程啊

**Comment by soulqw** [comment]
你好，反馈问题时候看看其他issue 有没有类似的提问，或者demo 中是否遗漏掉的部分，如果确实没有，把你测试场景、手机型号、系统版本、描述完整，不然很难定位问题

**Comment by Devil-AND** [comment]
AndroidStudio3.1版本，测试机型小米MIX2，8.0系统版本，简单的模拟直接拨打电话，使用的是您的1.1.7的依赖，直接Copy您的Demo代码，只走允许的情况，不走拒绝的情况，后来我修改了一下代码逻辑打印日志，依旧不走拒绝之后的逻辑！

**Comment by soulqw** [comment]
确认Android系统是8.0而不是MIUI 8.0
如果确认的话按照如下步骤：
1.不要忘记在Manifest中声明权限
2.卸载App重新安装，再次重试
3.可以设置debug 看下日志打印
如果是Android 6.0以下系统，此方法走允许是正常的

**Comment by Devil-AND** [comment]
再次尝试了MIUI8.0,Androidmanifest中已声名权限,试了一下你的demo,是可以的,但是转移到APP中就无效了,可是我试了一下新建demo,就可以,这是为啥

**Comment by soulqw** [comment]
细看下有哪里配置不一致吧
1.对比Manifest文件
2.对比Application
3.对比方法参数

**Comment by Devil-AND** [comment]
我试了试,在activity中的话是可以正常使用的,但是假如放在fragment中拒绝的监听就不管用!

**Comment by soulqw** [comment]
刚刚更新了1.1.8 优化了一下，提高了稳定性，你再试试

**Comment by Devil-AND** [comment]
刚刚试了一下1.1.8版本,发现一个偶尔出现的问题
机型MIX2,系统版本:8.0,测试权限:CallPhone
问题:有时申请权限时会出现没有"不再询问"这个选项,但是再试一次或几次就又有这个选项了

**Comment by soulqw** [comment]
这是系统设定，跟不同手机厂商的设定也有关系
