### ISSUE TITLE
在红米5A上，拒绝权限后，当前界面被关闭了，不知道什么情况啊

### ISSUE THREAD

**Issue by HenryBen** [soulqw/SoulPermission#13]
在红米5A上，拒绝权限后，当前界面被关闭了，不知道什么情况啊

**Comment by soulqw** [comment]
确认下Manifest是否有权限声明，再手动设置debug看下日志打印
如果有错误日志最好能提供一下，方便定位问题看问题

**Comment by HenryBen** [comment]
------------------ 原始邮件 ------------------
  发件人: "GeorgeQin"<notifications@github.com>;
 发送时间: 2019年6月15日(星期六) 下午4:53
 收件人: "soulqw/SoulPermission"<SoulPermission@noreply.github.com>;
 抄送: "安卓开发"<457042491@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [soulqw/SoulPermission] 在红米5A上，拒绝权限后，当前界面被关闭了，不知道什么情况啊 (#13)

 

 
Closed #13.
