### ISSUE TITLE
能供检查权限组的API么？

### ISSUE THREAD

**Issue by KaelInvoker** [soulqw/SoulPermission#15]
您好，能供检查某个权限组的API么？直接返回全部通过的结果，或者全部不通过。建议可以参考blankj库的写法，

**Comment by soulqw** [comment]
1.权限的申请，只要申请了组里面的一个，组里其他的都是直接授予的。比如你申请了 打电话权限，那么就可以直接获得同样属于改组的读取手机识别码的权限，这一点你可以参考demo
2.这边库提供的多个权限的功能是给位于不同分组的多个权限使用的，比如我拍照可能需要用到相机和存储权限，这个时候，就需要一次申请多个了
如果还有疑问，可以参考下博客中对运行时权限的探讨

**Comment by KaelInvoker** [comment]
大佬，我的意思是 我现在是不申请权限，只是想校验某个权限组有没有授予。比如说GROUP_LOCATION，这里面包含    permission.ACCESS_FINE_LOCATION, permission.ACCESS_COARSE_LOCATION。那我这边代码要怎么写呢？

**Comment by soulqw** [comment]
@KaelInvoker 
SoulPermission.getInstance().checkPermissions(Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION);
细节上可以看demo里面有注释的，另外 最新的1.1.8已经发布，增加了稳定性

**Comment by KaelInvoker** [comment]
感谢
