### ISSUE TITLE
腾讯乐固加固后不执行申请权限的问题

### ISSUE THREAD

**Issue by SwordSware** [soulqw/SoulPermission#16]
在使用中发现打出的release包，试运行，可以弹出权限，但是这个release包再用腾讯的乐固加固并签名后，再运行就出现权限申请不执行的问题，不知道什么原因，使用自带的权限申请方式正常

**Comment by soulqw** [comment]
有可能加固后会导致自动初始化失败，你尝试下在你的应用中Application中手动初始化试试SoulPermission.init

**Comment by SwordSware** [comment]
> 有可能加固后会导致自动初始化失败，你尝试下在你的应用中应用中手动初始化试试SoulPermission.init

好的，我试试

**Comment by SwordSware** [comment]
> 有可能加固后会导致自动初始化失败，你尝试下在你的应用中应用中手动初始化试试SoulPermission.init

试过了，确实这样可以了

**Comment by SwordSware** [comment]
> 有可能加固后会导致自动初始化失败，你尝试下在你的应用中应用中手动初始化试试SoulPermission.init

试过了，确实这样可以了

**Comment by SwordSware** [comment]
> > 有可能加固后会导致自动初始化失败，你尝试下在你的应用中应用中手动初始化试试SoulPermission.init
> 
> 谢谢

**Comment by masite** [comment]
0.0 这个问题我也遇到了，领导让打包 ，这个问题耽搁了好久。
