### ISSUE TITLE
权限请求会在android 6.0以下默认走成功回调

### ISSUE THREAD

**Issue by lhpliu** [soulqw/SoulPermission#17]
我是在请求摄像头拍照录像权限，时发现的问题，
测试手机为oppo android 5.1 请求拍照权限会调起是否允许的界面，未选择情况下，还是会执行后续操作，请大神指点

**Comment by soulqw** [comment]
首先6.0以下是Android是没有系统级Api去执行权限申请的，如果出现了是否允许，应该是厂商rom自己实现的权限系统，这边是无法知道的，故默认走成功回调

**Comment by lhpliu** [comment]
哦哦  多谢大神，我查了下  oppo跟vivo厂商6.0以下实现了自己的权限系统，汗一个
