### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by liyanshou** [soulqw/SoulPermission#18]
![Uploading image.png…]()
手动调用了init，也是失败

**Comment by soulqw** [comment]
你好，使用场景尽量描述清楚一些，不然不好定位问题

**Comment by soulqw** [comment]
不要在Application到onCreate调用权限请求，因为此时应用栈里面还没有Activity，此时SoulPermission调用就会报错,因为其中业务执行还是要依赖Activity才能执行

**Comment by wanhui123** [comment]
添加了腾讯tinker热更新插件 初始化失败了  注释插件 就可以成功

**Comment by soulqw** [comment]
加入了Tinker 以后，请手动在你的Application中调用 Soulpermission.init() 即可，细节上你可以细看Readme的注意事项
