### ISSUE TITLE
AppOpps判定不准确

### ISSUE THREAD

**Issue by wangmeng88525** [soulqw/SoulPermission#19]
您好，测试手机 Redmi Note3   Android版本 5.0.2发现以下问题
在设置中修改相机权限修改为“提示”时，checkAndRequestPermission判定结果为onPermissionDenied，能不能支持AppOpps可配置，或者直接6.0以下直接返回onPermissionOk？

**Comment by soulqw** [comment]
@wangmeng88525  你好，感谢反馈，后续可能会考虑加入这个判断，欢迎加群讨论：
[https://img-blog.csdnimg.cn/20190621184800806.png](url)

**Comment by soulqw** [comment]
@wangmeng88525 最新1.2.1 已经支持
