### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by snpmyn** [soulqw/SoulPermission#22]
红米机型跳转权限设置页面，设置权限后返回，应用闪退。

**Comment by soulqw** [comment]
@snpmyn 你好，错误反馈请贴上错误日志，以及系统版本，方便定位问题

**Comment by snpmyn** [comment]
> @snpmyn 你好，错误反馈请贴上错误日志，以及系统版本，方便定位问题

红米6A。我在网上搜了，红米机型在应用内部跳转权限设置页面，设置权限后，返回应用时，应用会出现重启现象，没有发现日志。应该是适配原因。
