### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by ContentPane** [soulqw/SoulPermission#23]
![image](https://user-images.githubusercontent.com/28483504/60872542-6fa61f80-a267-11e9-8ed6-7804824eaa1b.png)
![image](https://user-images.githubusercontent.com/28483504/60872577-7cc30e80-a267-11e9-9ecb-1ff0c926538f.png)
另外几个申请权限的页面也有内存泄漏的问题

**Comment by soulqw** [comment]
@ContentPane  我这边测试了下，正常使用情况下，没有发现上述泄漏，是否能贴一下你这边的使用场景，我这边再跟进一下

**Comment by ContentPane** [comment]
@soulqw 我用的Jetpack Navigaiton进行Fragment跳转 除此之外和正常Fragment一样

**Comment by ContentPane** [comment]
@soulqw 是不是NavController拦截了onBackPress()事件的原因
