### ISSUE TITLE
 Failed to resolve: com.qw:soulpermission:1.2.0

### ISSUE THREAD

**Issue by KaelInvoker** [soulqw/SoulPermission#24]
如题

**Comment by soulqw** [comment]
检查你的网络，我这边是ok的

**Comment by KaelInvoker** [comment]
![image](https://user-images.githubusercontent.com/37531571/61435066-3a39ba00-a96a-11e9-8f5c-58bb04f1d67e.png)
怪了，网络是通的，其它的依赖库升级都没问题

**Comment by KaelInvoker** [comment]
添上jcenter就好了。可我以前怎么能下载下来
