### ISSUE TITLE
能否设置强制开启权限功

### ISSUE THREAD

**Issue by appsming** [soulqw/SoulPermission#26]
在vivo手机上，系统弹窗后，用户禁止，不再提示； 当再次点击时，不显示出授权弹窗；

**Comment by appsming** [comment]
这个是一个小优化；

**Comment by soulqw** [comment]
你好，处理权限请求的是一套逻辑，应该和手机机型无关，除非厂商做了特殊处理，然后你这边问题描述感觉不是特别清晰，建议按照：
第X次调用    预期XXX  结果XXXX 格式反馈

**Comment by appsming** [comment]
您好，情况是这样的。仅在vivo手机上出现，如你要去打电话，点击狗弹出权限，你点击禁止按钮，你再去点击，也不弹窗，也不打电话，一点反应都没有。我查看了一下，系统是已经获取了权限的，只不过被vivo手机系统拦截了。我要表明的意思就是，现在的弹窗授权与系统的弹窗授权冲突了，导致自己的授权不起作用。这应该是个兼容性bug，我看到了有个开源库permission4m，该库作者已停止维护，但解决了上面产生的问题发自我的华为手机-------- 原始邮件 --------主题：Re: [soulqw/SoulPermission] 能否设置强制开启权限功 (#26)发件人：GeorgeQin 收件人：soulqw/SoulPermission 抄送：淡淡人生 ,Author 你好，处理权限请求的是一套逻辑，应该和手机机型无关，除非厂商做了特殊处理，然后你这边问题描述感觉不是特别清晰，建议按照：

第X次调用    预期XXX  结果XXXX 格式反馈

**Comment by appsming** [comment]
我找到问题了；https://blog.csdn.net/aabbwoshishei/article/details/76022152
原因是vivo手机里有个叫i管家的软件，他的权限控制优先级大于谷歌的；当需要调用打电话权限，i管家若不允许，那我们就无法去调用了；

**Comment by soulqw** [comment]
一般第三方手机自己实现的权限系统就没有办法了，因为适配也无法完全适配，这种情况下还是要以系统的结果为准
