### ISSUE TITLE
如图，点击允许权限，isGranted 返回的false

### ISSUE THREAD

**Issue by BergenWang** [soulqw/SoulPermission#28]
![图片](https://user-images.githubusercontent.com/18643187/62021948-7d165000-b1fc-11e9-9874-6094b422990f.png)

**Comment by soulqw** [comment]
1.确认下Manifest 是否声明了 READ_PHONE_STATE 权限
2.然后确认下你应用的targetSdk版本

**Comment by BergenWang** [comment]
> 
> 
> 1.确认下Manifest 是否声明了 READ_PHONE_STATE 权限
> 2.然后确认下你应用的targetSdk版本

targetSdk 27  ,Manifest 配置了的

**Comment by soulqw** [comment]
但是似乎权限情况和回调是一致的？
如果还有疑问的话可以加我微信讨论一下
Wei95012

**Comment by BergenWang** [comment]
> 
> 
> 但是似乎权限情况和回调是一致的？
> 如果还有疑问的话可以加我微信讨论一下
> Wei95012

试了一下，还是有上诉问题，但是只是在第一次回调会出现该问题，你可以试试。弹出权限授权Dialog时，点击允许，permmission.isGranted=false;

**Comment by soulqw** [comment]
那这个可能是特殊机型的问题了，你这边吧华为的系统版本发一下，我这边有测试机了再看下
。
然后既然已经走到了Ok 的回调，然后此时这个 isGranted 应该就没有必要再使用了吧？

**Comment by BergenWang** [comment]
> 
> 
> 那这个可能是特殊机型的问题了，你这边吧华为的系统版本发一下，我这边有测试机了再看下
> 。
> 然后既然已经走到了Ok 的回调，然后此时这个 isGranted 应该就没有必要再使用了吧？

是的，我没有使用isGranted，只是看到有这个问题，提一下。谢谢你。  
测试机型：Emui9.1.0 华为mate20 android 9
