### ISSUE TITLE
Android 5.1小米手机，申请相机权限，默认返回未授权

### ISSUE THREAD

**Issue by BergenWang** [soulqw/SoulPermission#29]
![图片](https://user-images.githubusercontent.com/18643187/62281397-494b5c80-b480-11e9-914a-78f6c6762c3f.png)
是否在不支持运行时权限的时候要特殊处理？

**Comment by soulqw** [comment]
这个功能后续会补上

**Comment by soulqw** [comment]
@BergenWang 最新1.2.1 已经支持
