### ISSUE TITLE
onCreate中调用，有时候会出现not attached to Activity

### ISSUE THREAD

**Issue by xiagea** [soulqw/SoulPermission#31]
Caused by java.lang.IllegalStateException
Fragment PermissionSupportFragment{887e6f3 (9c5e099d-054c-4bf9-9a52-0357cecc6cea) permission_fragment_tag} not attached to Activity

**Comment by sunkejing** [comment]
java.lang.IllegalStateException: Fragment PermissionSupportFragment{9091661 #0 permission_fragment_tag} not attached to Activity
这个问题导致不能正常申请权限

**Comment by soulqw** [comment]
@xiagea @sunkejing 
可否贴一下错误堆栈?

**Comment by xiagea** [comment]
androidx.fragment.app.Fragment.requestPermissions + 1306 (Fragment.java:1306)
--
  | com.qw.soul.permission.request.fragment.PermissionSupportFragment.requestPermissions + 47 (PermissionSupportFragment.java:47)
  | com.qw.soul.permission.request.fragment.FragmentProxy.requestPermissions + 28 (FragmentProxy.java:28)
  | com.qw.soul.permission.request.PermissionRequester.request + 76 (PermissionRequester.java:76)
  | com.qw.soul.permission.SoulPermission.requestRuntimePermission + 384 (SoulPermission.java:384)
  | com.qw.soul.permission.SoulPermission.access$000 + 33 (SoulPermission.java:33)
  | com.qw.soul.permission.SoulPermission$4.onStatusOk + 370 (SoulPermission.java:370)
  | com.qw.soul.permission.SoulPermission.checkStatusBeforeDoSomething + 363 (SoulPermission.java:363)
  | com.qw.soul.permission.SoulPermission.requestPermissions + 367 (SoulPermission.java:367)
  | com.qw.soul.permission.SoulPermission.checkAndRequestPermissions + 174 (SoulPermission.java:174)
  | com.smart_invest.marathonappforandroid.util.permission.PermissionUtil.checkPermission + 46 (PermissionUtil.java:46)
  | com.smart_invest.marathonappforandroid.view.activity.BaseActivity.onCreate + 91 (BaseActivity.java:91)
  | com.smart_invest.marathonappforandroid.view.activity.GuideActivity.onCreate + 38 (GuideActivity.java:38)

**Comment by soulqw** [comment]
@xiagea @sunkejing 这边看了下,我们这边一直在oncreate有调用,没有出现上述问题:
1.确认一下是否是使用方式问题,贴一下你们调用的代码
2.贴一下使用库的版本号

**Comment by xiagea** [comment]
版本:'com.qw:soulpermission:1.2.0_x'

onCreate()中
 @Override
    protected void onCreate(Bundle savedInstanceState) {
        if (Build.VERSION.SDK_INT == Build.VERSION_CODES.O && isTranslucentOrFloating()) {
            fixOrientation();
        }
        super.onCreate(savedInstanceState);
        setBinding(DataBindingUtil.setContentView(this, getContentViewLayoutId()));
        setDefaultStatusBarColor();
        init();
        initView(savedInstanceState);
        PermissionUtil.getInstance().checkPermission(this);
    }

PermissionUtil中
public void checkPermission(BaseActivity activity) {
        if (!(activity instanceof MainActivity) && !(activity instanceof SplashScreenActivity)) {
            SoulPermission.getInstance().checkAndRequestPermissions(
                    mPermissions,
                    new CheckRequestPermissionsListener() {
                        @Override
                        public void onAllPermissionOk(Permission[] allPermissions) {

                        }

                        @Override
                        public void onPermissionDenied(Permission[] refusedPermissions) {
                            onPermissionsCheck(refusedPermissions, activity);
                        }
                    });
        }
    }

mPermissions = Permissions.build(Manifest.permission.WRITE_EXTERNAL_STORAGE,
                Manifest.permission.READ_PHONE_STATE,
                Manifest.permission.ACCESS_FINE_LOCATION);


使用方式应该没问题，这种exception不是必现的，我自己也没碰到过

**Comment by soulqw** [comment]
@xiagea @sunkejing  大概了解了,也许是Android X 中的fragment的 bug ,你们这边先尝试着把X版本的版本升级到最新试试,我这边也在后续的版本中升级一下

**Comment by xiagea** [comment]
> @xiagea @sunkejing 大概了解了,也许是Android X 中的fragment的 bug ,你们这边先尝试着把X版本的版本升级到最新试试,我这边也在后续的版本中升级一下

好的，谢谢
