### ISSUE TITLE
小米4.4 存储权限 android.Manifest.permission.READ_EXTERNAL_STORAGE 返回false

### ISSUE THREAD

**Issue by listenwinding** [soulqw/SoulPermission#33]
存储权限android.Manifest.permission.READ_EXTERNAL_STORAGE 、android.Manifest.permission.WRITE_EXTERNAL_STORAGE 的检测问题
①在小米手机4.4的系统中 READ权限返回false ,WRITE权限返回true
②在华为手机4.4的系统中 READ权限返回true,WRITE权限返回true
③用系统的ContextCompat.checkSelfPermission(context, permission)方法检查时，在两个手机中READ权限和WRITE权限都返回true

原因：检查后发现是调用反射方法checkOp(int op)在两个手机中的结果不一致，关于这个有什么好的解决办法没？

**Comment by soulqw** [comment]
@listenwinding 初始化时候:  SoulPermission.skipOldRom(true); 默认让6.0以下所有权限不走AppOpps 直接授予
