### ISSUE TITLE
打基准包会出现问题

### ISSUE THREAD

**Issue by lhpliu** [soulqw/SoulPermission#34]
项目需要使用热更新，打基准包的时候会出现 获取权限无反应的情况 
ps：当时我是需要获取相机权限，点击后无反应，版本号是：1.2.2
改换成之前的老版本 1.1.8则可以申请成功

**Comment by soulqw** [comment]
应该和版本无关 ,你试试在应用Application中调用SoulPermission.init 再试试

**Comment by lhpliu** [comment]
我这边试了下，在热更新打基准包的情况下
版本号1.2.2的话，加上SoulPermission.init 就可以了  
版本号1.1.8 则不写也没关系。

**Comment by soulqw** [comment]
@lhpliu 应该和版本号无关而与热修复有关,你细看下Readme中的注意事项
