### ISSUE TITLE
校验提示文案、拒绝后不再提示入口

### ISSUE THREAD

**Issue by sadink** [soulqw/SoulPermission#4]
hi!
看了SoulPermission很赞，然遇到下面两个问题：
1、权限检测中弹层的提示文案需要可配置、
2、“点击【拒绝】后不再提示”功能入口是否启用可控

不知SoulPermission是否可以覆盖上面两点?

Thinks！

**Comment by zhupengxiang** [comment]
看下了demo，你说的这些都是在onPermissionDenied自己操作的

**Comment by soulqw** [comment]
自定义细节请看考下sample

**Comment by xuehuashi** [comment]
第一个问题，各大厂商都有自己的一套权限规则，文案各不相同，印象中好像见过权限授权弹框，自定义居中的，不记得哪个app那个手机，但是不是Google的那样，欢迎朋友知道的，给分享下涨个芝士。第二个问题，如2楼，多看demo

**Comment by soulqw** [comment]
我们能控制的部分只有demo中几个回调中可以自定义一些界面和用户引导，而请权限求弹框的文案是系统控制的(demo就是原生样式，比如小米最新系统请求弹框就在底部)，对于我们开发者而言不可定制，但是交互上是一致的。
@xuehuashi 
@sadink
