### ISSUE TITLE
跳转设置bug....，太不走心了

### ISSUE THREAD

**Issue by xuehuashi** [soulqw/SoulPermission#7]
看到这个库时，有点nice，但...
PermissionTools.class
1，vivo的doStartApplicationWithPackageName(context, "com.bairenkeji.icaller");白人科技包名从哪来？我抓到的vivo z1设置包，  //com.vivo.permissionmanager/com.vivo.permissionmanager.activity.SoftPermissionDetailActivity
代码可以用com.vivo.permissionmanager 。但是测试发现不行，不能跳到权限详情页，估计<intent-filter>  marked it as not exported。
2，小米判断，v567,v8,9,10,少个FLAG_ACTIVITY_NEW_TASK,否则会报错，还有那个return语句，严谨点哈
if ("V5".equals(rom) ||"V6".equals(rom) || "V7".equals(rom)) {
                intent.setAction("miui.intent.action.APP_PERM_EDITOR");
                intent.setClassName("com.miui.securitycenter", "com.miui.permcenter.permissions.AppPermissionsEditorActivity");
                intent.putExtra("extra_pkgname", context.getPackageName());
            } else if ("V8".equals(rom) || "V9".equals(rom) || "V10".equals(rom)) {
                intent.setAction("miui.intent.action.APP_PERM_EDITOR");
                intent.setClassName("com.miui.securitycenter", "com.miui.permcenter.permissions.PermissionsEditorActivity");
                intent.putExtra("extra_pkgname", context.getPackageName());
            } else {
                goOtherIntentSetting(context);
                return;
            }
            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            context.startActivity(intent);
3，doStartApplicationWithPackageName（）方法里，第一个catch里 逻辑少个return。
4， 其他几个品牌手机待验证，其他其他人补充下

**Comment by soulqw** [comment]
@xuehuashi 
感谢反馈，问题会在下个迭代修复。
1.这部分代码源于我们项目中原有的权限跳转，可能覆盖的机型不够广泛，如果有更好的适配跳转，欢迎提Pull Request
2.鉴于Android碎片化的严重的问题，适配难以全部涵盖，我这边计划换一个思路：直接跳转到应用详情页去管理权限

**Comment by kystudio** [comment]
华为的，应该是下面那个吧？ 单个app的权限设置
//            ComponentName comp = new ComponentName("com.huawei.systemmanager", "com.huawei.permissionmanager.ui.MainActivity");
            ComponentName comp = new ComponentName("com.huawei.systemmanager", "com.huawei.permissionmanager.ui.SingleAppActivity");

**Comment by soulqw** [comment]
最新1.1.7已经上传
@xuehuashi 
@kystudio
