### ISSUE TITLE
暂时没有发现异常，但是有个问题想要请教大神

### ISSUE THREAD

**Issue by fanzhiqiang123** [soulqw/SoulPermission#8]
在用户拒绝请求后我让他直接跳转到设置页面手动打开权限，然后他并没有手动打开，直接点击back键返回到权限请求页面,这种情况不执行oncreate 方法，那么在onresume方法中应该如何处理？请大神指点。

**Comment by soulqw** [comment]
1.尽量不要在onResume中请求权限，用户体验不好，推荐使用的时候申请，参考demo中打电话的方法。
2.如果是特别必要的权限，比如存储和手机识别码的权限，推荐你参考网易云音乐初次安装的权限请求流程。

**Comment by fanzhiqiang123** [comment]
好的，感谢大神回复------------------ 原始邮件 ------------------
发件人: "GeorgeQin"<notifications@github.com>
发送时间: 2019年5月31日(星期五) 晚上6:47
收件人: "soulqw/SoulPermission"<SoulPermission@noreply.github.com>;
抄送: "fanzhiqiang123"<1436119974@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [soulqw/SoulPermission] 暂时没有发现异常，但是有个问题想要请教大神 (#8)



1.尽量不要在onResume中请求权限，用户体验不好，推荐使用的时候申请，参考demo中打电话的方法。
 2.如果是特别必要的权限，比如存储和手机识别码的权限，推荐你参考网易云音乐初次安装的权限请求流程。
 
&mdash;

**Comment by weifengteng** [comment]
灰常棒👍 点赞

**Comment by leifu1107** [comment]
读了上面的有些### **疑问?网易云音乐初次安装的权限**,
当用户拒绝权限并且不再提醒时,网易云会有个跳到设置界面打开对应的权限,权限打开后返回可以自动跳转到网易云的主页面,但是你的如果调到设置页面并打开权限返回怎么办呢?是否提供一下对应代码供大家参考?现在很多app启动时候都需要强制打开一些权限的

**Comment by soulqw** [comment]
[1.1.7](https://github.com/soulqw/SoulPermission/releases)中提供了跳转应用设置页设置requestCode，
当用户点拒绝且“不再提示”以后，回到应用的时候你可以在onActivityResult中再检查一次你所需要的权限，如果授予了就执行后续操作哈。
ps：这个跳转到应用页再回来检查被”不再提示“权限的功能正在酝酿中，跟请求特殊权限的流程差不多，会在后续版本加上。

**Comment by soulqw** [comment]
@leifu1107 
[1.1.7](https://github.com/soulqw/SoulPermission/releases)中提供了跳转应用设置页设置requestCode，
当用户点拒绝且“不再提示”以后，你可以引导用户跳转到应用设置页，当再次回到应用的时候你可以在onActivityResult中再检查一次你所需要的权限，如果授予了就执行后续操作哈。
ps：这个跳转到应用页再回来检查被”不再提示“权限的功能正在酝酿中，跟请求特殊权限的流程差不多，会在后续版本加上。

**Comment by soulqw** [comment]
最新[1.1.8](https://github.com/soulqw/SoulPermission/releases/tag/1.1.8)跳转到应用详情支持回调了
@leifu1107
